"""add_missing_fields_product_user

Revision ID: 51876c60a547
Revises: f9296087169a
Create Date: 2026-01-29 15:09:12.716269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51876c60a547'
down_revision: Union[str, None] = 'f9296087169a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lot_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_period_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('credit_period_days')

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('lot_number')

    # ### end Alembic commands ###
