"""Expand models for brand order and cart items

Revision ID: 79a76375c4fc
Revises: a214cc1b501f
Create Date: 2026-01-25 21:45:51.523226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a76375c4fc'
down_revision: Union[str, None] = 'a214cc1b501f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_orders_address_id_addresses'), 'addresses', ['address_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_products_brand_id_brands'), 'brands', ['brand_id'], ['id'])
        batch_op.drop_column('brand')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_products_brand_id_brands'), type_='foreignkey')
        batch_op.drop_column('brand_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orders_address_id_addresses'), type_='foreignkey')

    # ### end Alembic commands ###
